# Generated by Django 3.2.25 on 2025-02-22 09:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My title', max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=190, null=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
