# Generated by Django 3.2.25 on 2025-02-25 15:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='my title', max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=190, null=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
    ]
